services:
  web:
    build: ./web
    ports:
      - 443:9090
    networks:
      - backend
  api:
    build: ./api
    env_file: ./.env
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    volumes:
      - ./api:/opt/src
    networks:
      - backend
networks:
  backend:
    name: backend
