spring.application.name:
  - interest.calculator

server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"